#include<iostream>
using namespace std;
main(){
	int no1;
	int no2;
	int no3;
	int no4;
	int no5;
	int no6;
	int no7;
	int no8;
	int no9;
	int no10;
	int no11;
	int no12;
	int no13;
	int no14;
	int no15;
	int add5;
	int multiply5;
	int subtract5;
	int addandmultiply;
	int subtract;
	cout<<"Number 1: ";
	cin>> no1;
	cout<<"Number 2: ";
	cin>>no2; 
	cout<<"Number 3: ";
	cin>>no3;
	cout<<"Number 4: ";
	cin>>no4;
	cout<<"Number 5: ";
	cin>>no5;
	cout<<"Number 6: ";
	cin>>no6;
	cout<<"Number 7: ";
	cin>>no7;
	cout<<"Number 8: ";
	cin>>no8;
	cout<<"Number 9: ";
	cin>>no9;
	cout<<"Number 10: ";
	cin>>no10;
	cout<<"Number 11: ";
	cin>>no11;
	cout<<"Number 12: ";
	cin>>no12;
	cout<<"Number 13: ";
	cin>>no13;
	cout<<"Number 14: ";
	cin>>no14;
	cout<<"Number 15: ";
	cin>>no15;
	add5=no1+no2+no3+no4+no5;
	multiply5=no6*no7*no8*no9*no10;
	subtract5=no11-no12-no13-no14-no15;
	addandmultiply=add5+multiply5;
	subtract=addandmultiply-subtract5;
	cout<<"The final result is: ";
	cout<<subtract;

}

